zalando/dress-code

docs/demo/materials/atoms/buttons/06-button--groups.html, src/styles/modules/_btn.scss
- Add possibility to put several button groups in one line (button group row)
- Fix stroke-color behaviour for primary buttons that are not :first-child
- Change text in group standard buttons from "Secondary" to "Standard"
=> feat(buttons): Improve and extend button groups #16

README.md, package.json, src/styles/_base.scss, src/styles/_import.scss
=> Be strict with node and npm version

docs/demo/assets/fabricator/styles/partials/_exceptions.scss, docs/demo/materials/atoms/loading-bar.html, src/styles/modules/_loading-bar.scss, src/styles/toolkit.scss
=> feat(loading-bar) Add loading bar atom

docs/demo/materials/atoms/divider.html, src/styles/modules/_divider.scss, src/styles/toolkit.scss
A simple divider to separate sections.
=> feat(divider): Create a simple section divider

docs/demo/assets/fabricator/scripts/fabricator.js, docs/demo/assets/fabricator/scripts/interactions.js, docs/demo/materials/molecules/button-dropdown.html, docs/demo/views/layouts/default.html, src/styles/modules/_btn.scss, src/styles/modules/_dropdown.scss, src/styles/toolkit.scss
- Add dropdown and dropup menu to buttons
- Add separators between drop items
- Make drop items inactive
=> feat(dropdown): Add dropdown/dropup button molecule

docs/demo/materials/02-atoms/card.html, src/styles/atoms/_card.scss, src/styles/dress-code.scss
=> feat(card): add card atom, close #107

docs/demo/materials/02-atoms/status.html, src/styles/atoms/_status.scss, src/styles/dress-code.scss
Add the status indicator atom to Dress Code.
=> feat(status): Define status indicator atom. Close #96.

docs/demo/views/index.html
Fix an embarrassing typo in the demo main page.
=> fix(demo): Fix typo in demo

docs/demo/assets/fabricator/styles/partials/_exceptions.scss, src/styles/atoms/_btn.scss, src/styles/atoms/_checkbox.scss, src/styles/atoms/_radio.scss
Ensure compatibility between table and:
- Button
- Checkbox and switch
- Radio
- Select
Note: the default bottom-margin of buttons has been removed. Check your layouts when upgrading.
=> feat(table): Add compatibility btwn table and atoms. Close #90

src/styles/atoms/_list.scss
=> fix(lists): move scrollable list item action icon to right side. 

docs/demo/assets/styles/partials/_layout.scss
use scrollbar of page for deep link navigation
=> fix(deep-linking) remove inner scroll of f-container

docs/demo/materials/02-atoms/icons.html
@cjhowald @dami-gg please review.
=> docs(icons): enhance notes for icon usage, close #106

docs/demo/assets/styles/partials/_item.scss, docs/demo/assets/styles/partials/_sg-section.scss, docs/demo/materials/02-atoms/select.html, src/styles/atoms/_select.scss
- Add disabled state to select.
- Modify padding to add 4px to select's height, to match buttons and other basic atoms.
Close #187. Close #189.
=> feat(select): Add disabled and match height with other atoms.

docs/demo/materials/02-atoms/buttons/03-options.html, src/styles/atoms/_btn.scss
=> feat(buttons): Add active button option

src/icons/arrow-left.svg, src/icons/arrow-right.svg
=> feat(icons): Update left and right arrow icons.

src/styles/molecules/_dialog.scss
=> fix(dialog): Fix padding of button zone

docs/demo/assets/scripts/fabricator.js, docs/demo/assets/styles/partials/_code.scss, docs/demo/assets/styles/partials/_grid.scss, docs/demo/assets/styles/partials/_item.scss, docs/demo/assets/styles/partials/_layout.scss, docs/demo/assets/styles/partials/_menu.scss, docs/demo/assets/styles/partials/_variables.scss, docs/demo/materials/02-grid/01-Grid/02-shrink-columns.html, docs/demo/materials/02-grid/01-Grid/07-nested-grid-rows.html, docs/demo/views/index.html, docs/demo/views/layouts/default.html, docs/demo/views/layouts/includes/f-item.html, src/styles/atoms/_card.scss, src/styles/grid/_grid-classes.scss, src/styles/grid/_grid-mixins.scss, src/styles/molecules/_tooltip.scss
- Stop menu from animating when changing pages
- Simplify menu CSS and responsive behavior
- Clean up some text in various sections
- Add color to grid demo
- Make groups look like dc-card
- Additional miscellaneous corrections & linting
=> feat(demo): Various demo improvements

src/styles/molecules/_dialog.scss
=> fix(dialog): fix broken overlay in chrome in retina displays

docs/demo/assets/styles/partials/_item.scss, docs/demo/assets/styles/partials/_layout.scss
=> feat(demo): Style links as dc-link

src/styles/atoms/_btn.scss, src/styles/atoms/_checkbox.scss, src/styles/atoms/_radio.scss
=> feat(cursors): Use pointer cursor for buttons, checkboxes and radios

docs/demo/materials/03-atoms/icons/01-icons.html, src/icons/arrow-down.svg, src/icons/arrow-up.svg, src/icons/minus.svg, src/img/svg-icons/arrow-down.svg, src/img/svg-icons/arrow-up.svg, src/img/svg-icons/minus.svg, src/styles/_generated/_icon.scss
#253 
Added icons:
- Minus icon
- Arrow up
- Arrow down
=> feat(icons): Add more icons

docs/demo/materials/03-atoms/tables/01-table-setup.html, docs/demo/materials/03-atoms/tables/02-sortable-headings.html, docs/demo/materials/03-atoms/tables/03-spacing-modifiers.html, src/styles/atoms/_table.scss
@sambhav-gore @xonic Please check this out your input would be appreciated!
=> feat(tables): Add sortable header

docs/demo/assets/styles/partials/_sg-icon.scss, docs/demo/materials/03-atoms/icons/01-icons.html, src/icons/triangle-down.svg, src/icons/triangle-up.svg, src/styles/_generated/_icon.scss
=> feat(icons): add triangle up and down icons

src/styles/molecules/_messages.scss, src/styles/molecules/_toast.scss
=> feat(messages): Align colors of messages and toasts

.zappr.yaml
=> chore(zappr): require approval of Norris+UX to merge

src/styles/molecules/_accordion.scss, src/styles/molecules/_tooltip.scss
=> fix(accordion): remove triangle icon, use border hack instead

src/styles/molecules/_dialog.scss
Closes #294 
@rbarilani @sambhav-gore @gabrielhl Is this update cool with you guys? Do you foresee any issues by adding this back in?
=> refactor(dialog): add missing mixin to prevent breaking changes

CHANGELOG.md, package.json, src/styles/_generated/_icon.scss
Ok guys I created the branch... 
If it's ok. I would leave you the responsability to:
* add the tag 
* merge develop into master
* publish to npm and bower
@gregdeane @sambhav-gore @frontendherodk 
an issue related to releasing is already open: #293 ... we should improve the process because it's not so straight forward
=> chore(release): 2.0.0-beta.1

.zappr.yaml
=> chore(config): remove UX from zappr approval

docs/demo/materials/03-atoms/divider.html, src/styles/atoms/_divider.scss
=> feat(divider): add secondary divider

docs/demo/materials/04-molecules/05-search-form.html, src/styles/molecules/_search-form.scss
=> bug(search): remove native date field clear button

docs/demo/materials/04-molecules/10-messages.html, src/styles/molecules/_messages.scss, src/styles/molecules/_toast.scss
- Align colors between messages and toasts
- Use variable for border-width. 
- Fix missing border-width.
Close #329.
=> feat(messages): Update design of messages

docs/guides/CONTRIBUTING.md, docs/guides/RELEASING.md
=> docs(contributing): remove develop branch

docs/demo/materials/02-structure-and-grid/02-grid/10-hide-or-show-elements.html, src/styles/structure/_grid-classes.scss
=> feat(grid): Add utility classes to hide/show at different breakpoints

src/styles/atoms/_btn.scss, src/styles/atoms/_checkbox.scss, src/styles/atoms/_list.scss, src/styles/atoms/_radio.scss, src/styles/atoms/_select.scss
=> fix(style): Standardise elements height to 2.4rem

.gitignore, README.md
docs(oss): add work in progress on oss readme enhancements
=> docs(oss): add work in progress on oss readme enhancements

docs/demo/materials/02-structure-and-grid/01-page-structure.html
=> docs(page-structure): updated documentation

.travis.yml, README.md, docs/demo/materials/03-atoms/tab.html, package.json, src/styles/atoms/_tab.scss, src/styles/core/_variables.scss, src/styles/dress-code.scss
Closes #238 
@gabrielhl I have made the changes as per the input on the issue, please review.
=> Add tab atom to dress code

docs/demo/materials/03-atoms/forms/textarea.html, src/styles/atoms/_textarea.scss
=> feat(textarea): add styles for error state

docs/demo/materials/03-atoms/tables/02-sortable-headings.html, docs/demo/materials/03-atoms/tables/03-spacing-modifiers.html, src/styles/atoms/_table.scss
=> fix(table): fix possible overlapping of sorters

CHANGELOG.md, package.json, src/styles/_generated/_icon.scss
=> chore(release): 2.1.0

docs/demo/materials/03-atoms/forms/text-input.html, src/styles/atoms/_input.scss, src/styles/atoms/_select.scss
=> feat(text-input): add small modifier

MAINTAINERS
chore(maintainers): remove colin
close #365
=> chore(maintainers): update maintainers

src/styles/core/_normalize.scss
=> fix(input): search input to have box-sizing of border-box

src/styles/molecules/_dialog.scss
=> feat(dialog): set max-height for body and add scroll bar

README.md, docs/demo/materials/01-core/04-scss-reference.html
#388 Adds information about dc-font-path and dc-image-path variables
=> Add information about variables for build

CHANGELOG.md, package.json, src/styles/_generated/_icon.scss
=> chore(release): 2.2.0

CHANGELOG.md, package.json, src/styles/_generated/_icon.scss
=> chore(release): 2.3.0

docs/demo/assets/scripts/quick-search.js
=> docs(search): make search work with basepath

docs/demo/materials/03-atoms/tab.html, src/styles/atoms/_tab.scss
=> feat(tab): add tab header element

CHANGELOG.md, package-lock.json, package.json, src/styles/_generated/_icon.scss, tests/screenshots/baseline/side-revealer/08-side-revealer__desktop.png, tests/screenshots/baseline/side-revealer/08-side-revealer__mobile.png
=> chore(release): 2.4.0

README.md, gulp/demo.js
- Removed empty pipe
- Updated readme with correct names for npm commands
=> chore(demo): fix demo deploy gulp task
